version: '3.8'

services:
  portainer:  
    image: portainer/portainer-ce:lts
    command: >
      sh -c "while [ ! -d /data ]; do echo 'Waiting for /data to be mounted...'; sleep 3; done;
             exec /portainer -H tcp://tasks.portainer_agent:9001 --tlsskipverify"
    ports:
      - target: 9443
        published: 9443
        mode: host
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - type: bind
        source: /data/shared/portainer_data
        target: /data
        read_only: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 200M
          cpus: '0.5'
        reservations:
          memory: 100M
          cpus: '0.25'
      labels:
        - com.example.stack-secured=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:9443"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  agent:
    image: portainer/agent:lts
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
        read_only: true
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
          cpus: '0.25'
        reservations:
          memory: 50M
          cpus: '0.10'

networks:
  agent_network:
    driver: overlay
    attachable: false


